<div id="overlay" class="overlay"></div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready( function() {
            $( ".showcart" ).click(function() {
                //$('#overlay').addClass('active-overlay');
            });
            $( "#btn-minicart-close" ).click(function() {
                //$('#overlay').removeClass('active-overlay');
            });

        });
    });
</script>